import rotterdam  from './cities/rotterdam.js';
import groningen  from './cities/groningen.js';
import denHaag    from './cities/den-haag.js';
import amsterdam  from './cities/amsterdam.js';
import utrecht    from './cities/utrecht.js';
import arnhem     from './cities/arnhem.js';
import nijmegen   from './cities/nijmegen.js';
import zwolle     from './cities/zwolle.js';
import eindhoven  from './cities/eindhoven.js';
import amersfoort from './cities/amersfoort.js';
import breda      from './cities/breda.js';
import assen      from './cities/assen.js';
import delft      from './cities/delft.js';
import haarlem    from './cities/haarlem.js';
import zandvoort  from './cities/zandvoort.js';
import oss        from './cities/oss.js';
import voorschoten from './cities/voorschoten.js';
import deventer    from './cities/deventer.js';

export const CITIES = { rotterdam, groningen, 'den-haag': denHaag, amsterdam, utrecht, arnhem, nijmegen, zwolle, eindhoven, amersfoort, breda, assen, delft, haarlem, zandvoort, oss, voorschoten, deventer };
